"""Command-line interface for ProofSentinel.

Stage 2 covers argument parsing and exit codes only. The commands are
recognised but not implemented yet, so they fail closed with exit code 2
instead of reporting a pass.
"""

import argparse
import sys
from collections.abc import Sequence
from enum import IntEnum
from pathlib import Path
from typing import NoReturn


class ExitCode(IntEnum):
    """Process exit codes defined by the v0.1 contract."""

    OK = 0  # all checks passed
    CHECKS_FAILED = 1  # one or more declared checks failed
    ERROR = 2  # manifest, safety, execution or evidence error
    USAGE = 3  # command-line usage error


class UsageError(Exception):
    """Raised when the command line is invalid."""

    def __init__(self, usage: str, prog: str, message: str) -> None:
        super().__init__(message)
        self.usage = usage
        self.prog = prog
        self.message = message


def _escape_controls(text: str) -> str:
    """Return text that is safe to print: non-printable characters become visible escapes."""
    return "".join(
        ch if ch.isprintable() else ch.encode("unicode_escape").decode("ascii") for ch in text
    )


class _ArgumentParser(argparse.ArgumentParser):
    """ArgumentParser that raises UsageError instead of printing and exiting."""

    def error(self, message: str) -> NoReturn:
        raise UsageError(self.format_usage(), self.prog, message)


def build_parser() -> argparse.ArgumentParser:
    """Build the argument parser. Parsing never touches the filesystem."""
    parser = _ArgumentParser(
        prog="proofsentinel",
        description="Offline-first deterministic security testing and evidence harness.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate = subparsers.add_parser(
        "validate", help="validate a manifest without running anything"
    )
    validate.add_argument("manifest", type=Path, help="path to the manifest file")

    run = subparsers.add_parser("run", help="run a manifest and write a new evidence directory")
    run.add_argument("manifest", type=Path, help="path to the manifest file")
    run.add_argument(
        "--output",
        type=Path,
        required=True,
        help="new evidence directory (must not already exist)",
    )

    verify = subparsers.add_parser("verify-evidence", help="verify an existing evidence directory")
    verify.add_argument("evidence_directory", type=Path, help="path to the evidence directory")

    return parser


def _not_implemented(command: str) -> int:
    """Report an unimplemented command. Fails closed: never returns a success code."""
    print(
        f"proofsentinel: '{command}' is not implemented yet (v0.1 is under development).",
        file=sys.stderr,
    )
    return ExitCode.ERROR


def main(argv: Sequence[str] | None = None) -> int:
    """Run the command line and return a process exit code.

    Bad usage returns ExitCode.USAGE (3) with a message on stderr, never a traceback.
    """
    arguments = list(sys.argv[1:] if argv is None else argv)
    parser = build_parser()
    try:
        namespace = parser.parse_args(arguments)
    except UsageError as exc:
        # The usage text is generated by the program. The message can echo what the
        # user typed, so make control characters visible before printing it.
        print(exc.usage, end="", file=sys.stderr)
        print(f"{exc.prog}: error: {_escape_controls(exc.message)}", file=sys.stderr)
        return ExitCode.USAGE
    except SystemExit as exc:
        # argparse raises SystemExit(0) after printing --help. Anything else is
        # unexpected, so fail closed with the usage code.
        return ExitCode.OK if exc.code in (0, None) else ExitCode.USAGE
    return _not_implemented(str(namespace.command))